### ISSUE TITLE
Size Function doesn't seem to work on Forge (1.19.2 +1)

### ISSUE THREAD

**Issue by Bluthirn** [CaiganMythFang/Anthro_Origins#5]
I added "[TFB] Anthro Origins" to a modpack with many other Origins addons. I noticed that the size of Origins like Mouse, Rat or Ferret doesn't change.

Naturally I first thought that it was an incompatibility with an another addon. But after trying it only with the base "Origins" mod installed, I noticed that it still doesn't work.

After further testing on other environments (Fabric 1.19.2 +1, Forge 1.18.2 +1), it seems to be an issue sole with Forge 1.19.2 +1.

**Comment by CaiganMythFang** [comment]
Is the Pehkui mod installed as well? (It should be a required dependency for all versions)

**Comment by Bluthirn** [comment]
It is

**Comment by Bluthirn** [comment]
Nevermind wrong Loader. Thank's for the Help.
