### ISSUE TITLE
[Forge] Added mod to mod folder, can select class, nothing happens when using ability

### ISSUE THREAD

**Issue by jrbuda** [CaiganMythFang/Anthro_Origins#6]
I added this mod to the mod pack I am playing, medieval mc 1.19.2 forge, and can see and select the classes but when I select a class with an active, the wolf for example, and press [g] nothing happens. No buff, no sound play, etc. 
I put the mod in the mods folder and the data in saves>world>data. This is single player for testing. I will want to use it on my actual server when I start that up after testing it out.
Please let me know if I am missing a step or if installation guides exist anywhere, thanks!

**Comment by CaiganMythFang** [comment]
Double check if there are conflicting keybinds.

**Comment by jrbuda** [comment]
The classes that come with the pack work perfectly fine but the ones added through this mod don't work properly. The log also doesn't show any errors.
No keybind issues either

**Comment by jrbuda** [comment]
I do receive most of the passive effects. I changed my origin to ones that don't get hurt on touching a cactus and I took no damage but still could not use the active ability. I double checked settings and only see the one Origins activate ability keybind.

**Comment by CaiganMythFang** [comment]
Okay, I think I know what might going on, after testing it on my own with what I think is the pack you mentioned.

One of the mods in Medieval MC (Forge) adds what looks to be a hydration bar. This blocks the recharge bar image for the active abilities of many origins. When you first choose an origin with an active ability that has a cooldown, it isn't immediately available and starts in cooldown.

![image](https://github.com/CaiganMythFang/Anthro_Origins/assets/16909199/b22dd1f7-5c4f-47e8-bb14-0d87bcac84a8)

You can see a progress bar behind the water droplets

**Comment by jrbuda** [comment]
Let me edit around my UI and wait out the period.

**Comment by jrbuda** [comment]
Yep that did it! I was having an issue where the elephant is not doing the 2 step block height but I think I will just give origin orbs to people who experience small quirks like that. Thanks for taking the time to download the modpack and see what was up.

**Comment by jrbuda** [comment]
closed
