### ISSUE TITLE
Attack Damage Modifier causing crash on Fabric for MC 1.17.1

### ISSUE THREAD

**Issue by Person4772** [CaiganMythFang/Anthro_Origins#7]
Since the latest Fabric loader update, the 1.17.1 version of Anthro Origins has been crashing an Aternos server that i am a part of. the error log loads as normal but crashes when it reaches "tfb2". Log pasted below:

> [15:10:53] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.15.7
> [15:10:54] [ForkJoinPool-1-worker-1/WARN]: The mod "tfb2" contains invalid entries in its mod json:
> - Unsupported root entry "pack_format" at line 14 column 18
> [15:10:54] [main/INFO]: Loading 58 mods:
> 	- extraorigins 1.17-11
> 	- fabric 0.46.1+1.17
> 	   |-- fabric-api-base 0.4.0+cf39a74318
> 	   |-- fabric-api-lookup-api-v1 1.5.0+e821752d18
> 	   |-- fabric-biome-api-v1 3.2.2+cf39a74318
> 	   |-- fabric-blockrenderlayer-v1 1.1.6+cf39a74318
> 	   |-- fabric-command-api-v1 1.1.4+cf39a74318
> 	   |-- fabric-commands-v0 0.2.3+cf39a74318
> 	   |-- fabric-containers-v0 0.1.13+cf39a74318
> 	   |-- fabric-content-registries-v0 0.4.1+3447790d18
> 	   |-- fabric-crash-report-info-v1 0.1.6+cf39a74318
> 	   |-- fabric-dimensions-v1 2.0.15+b556f28c18
> 	   |-- fabric-entity-events-v1 1.4.1+377137cc18
> 	   |-- fabric-events-interaction-v0 0.4.12+e99fbe1218
> 	   |-- fabric-events-lifecycle-v0 0.2.4+cf39a74318
> 	   |-- fabric-game-rule-api-v1 1.0.8+cf39a74318
> 	   |-- fabric-item-api-v1 1.3.0+6617390918
> 	   |-- fabric-item-groups-v0 0.3.2+cf39a74318
> 	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
> 	   |-- fabric-keybindings-v0 0.2.4+cf39a74318
> 	   |-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
> 	   |-- fabric-loot-tables-v1 1.0.5+cf39a74318
> 	   |-- fabric-mining-level-api-v1 1.0.3+cf39a74318
> 	   |-- fabric-mining-levels-v0 0.1.7+cf39a74318
> 	   |-- fabric-models-v0 0.3.1+cf39a74318
> 	   |-- fabric-networking-api-v1 1.0.14+cf39a74318
> 	   |-- fabric-networking-blockentity-v0 0.2.12+cf39a74318
> 	   |-- fabric-networking-v0 0.3.3+cf39a74318
> 	   |-- fabric-object-builder-api-v1 1.11.1+f907116918
> 	   |-- fabric-object-builders-v0 0.7.8+cf39a74318
> 	   |-- fabric-particles-v1 0.2.5+cf39a74318
> 	   |-- fabric-registry-sync-v0 0.8.0+ea29b33318
> 	   |-- fabric-renderer-api-v1 0.4.6+ce16ae5918
> 	   |-- fabric-renderer-indigo 0.4.10+ce16ae5918
> 	   |-- fabric-renderer-registries-v1 3.2.6+cf39a74318
> 	   |-- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318
> 	   |-- fabric-rendering-fluids-v1 0.2.1+cf39a74318
> 	   |-- fabric-rendering-v0 1.1.7+cf39a74318
> 	   |-- fabric-rendering-v1 1.10.1+377137cc18
> 	   |-- fabric-resource-conditions-api-v1 1.0.1+591a0f2118
> 	   |-- fabric-resource-loader-v0 0.4.10+f09604ce18
> 	   |-- fabric-screen-api-v1 1.0.5+cf39a74318
> 	   |-- fabric-screen-handler-api-v1 1.1.9+cf39a74318
> 	   |-- fabric-structure-api-v1 1.2.0+48a9ad8918
> 	   |-- fabric-tag-extensions-v0 1.2.3+cf39a74318
> 	   |-- fabric-textures-v0 1.0.7+cf39a74318
> 	   |-- fabric-tool-attribute-api-v1 1.3.3+3b96517518
> 	   \-- fabric-transfer-api-v1 1.5.4+cf39a74318
> 	- fabric-tpa 3.0.1
> 	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
> 	- fabrichomes 2.0.0
> 	- fabricloader 0.15.7
> 	   \-- mixinextras 0.3.5
> 	- java 16
> 	- minecraft 1.17.1
> 	- origins 1.1.4
> 	   |-- apoli 2.0.5
> 	   |    |-- calio 1.3.0
> 	   |    |-- cardinal-components-base 3.1.1
> 	   |    |-- cardinal-components-entity 3.1.1
> 	   |    |-- cloth-config2 5.0.34
> 	   |    |    \-- cloth-basic-math 0.5.1
> 	   |    |-- fallflyinglib 3.0.0-beta.2
> 	   |    \-- playerabilitylib 1.3.0
> 	   \-- reach-entity-attributes 2.1.1
> 	- originsumbrellas 1.3.0
> 	- pehkui 3.6.3+1.14.4-1.19.3
> 	   \-- kanos_config 0.3.1+1.14.4-1.19
> 	- tfb2 1.6.0
> [15:10:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
> [15:10:55] [main/INFO]: Compatibility level set to JAVA_16
> [15:10:58] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
> [15:11:17] [main/ERROR]: Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: ATTACK_DAMAGE_MODIFIER
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.7.jar:?]
> Caused by: java.lang.NoSuchFieldError: ATTACK_DAMAGE_MODIFIER
> 	at net.minecraft.class_1799.<clinit>(class_1799.java:130) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1761.<init>(class_1761.java:115) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1761$1.<init>(class_1761.java:16) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1761.<clinit>(class_1761.java:16) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1802.<clinit>(class_1802.java:21) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2378.method_10234(class_2378.java:176) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2378.method_34031(class_2378.java:275) ~[server-intermediary.jar:?]
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
> 	at net.minecraft.class_2378.<clinit>(class_2378.java:274) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2966.method_12851(class_2966.java:44) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.Main.main(Main.java:92) ~[server-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
> 	... 3 more

**Comment by CaiganMythFang** [comment]
Greetings!

The listed error about tfb2 containing invalid entries is about the mod config file having an extra entry that it is ignoring, and doesn't prevent the mod from loading.

The crash happens after all mods have loaded (Which is why TFB2 is at the bottom of the list, its alphabetical)

Could you get me the full latest.log from your logs folder after the crash? I'm testing with all of the mods listed in your crash report above, and am not getting the same crash issue. 

As well, does the server still crash if Anthro Origins is disabled?

**Comment by Person4772** [comment]
This server is being run on Aternos, and i cannot seem to find any file named latest.log
The Logfile is here: [Log1](https://mclo.gs/dgA31nA)
I updated all the other mods to their latest versions and got this log: [Log2](https://mclo.gs/Vu1KO3t)

The game still crashed as well

**Comment by CaiganMythFang** [comment]
Have you tried disabling Anthro Origins on both the server client and seeing if it still crashes on loading?

**Comment by Person4772** [comment]
The server does still crash with the mod disabled. [Log](https://mclo.gs/rEwsyxm)

**Comment by CaiganMythFang** [comment]
Most of what I could find for you is that it might be Extra Origins causing the issue. Try disabling that and see if that helps

**Comment by Person4772** [comment]
I'll do that, Thanks for the Help!
